import { useCallback,useEffect,useMemo,useState } from "react";
import type { ConcertPersonalMemory,ConcertPersonalMemoryDraft } from "./concert-personal-memory";
import { useAuth } from "./auth"; import { getCloudConcertMemory,saveCloudConcertMemory } from "./concert-personal-memory.cloud"; import { ensureEventMigration } from "./events.source"; import { isDataUrl,uploadImage } from "./storage";
const KEY="idoldays.concertPersonalMemories.v1",MIGRATION_KEY="idoldays.cloudMigration.concertMemories.v1";
function read():ConcertPersonalMemory[]{if(typeof window==="undefined")return[];try{const p=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(p)?p:[]}catch{return[]}}
function write(v:ConcertPersonalMemory[]){localStorage.setItem(KEY,JSON.stringify(v))}
export function useConcertPersonalMemory(eventId?:string,idolId?:string){const {user,loading}=useAuth();const [entry,setEntry]=useState<ConcertPersonalMemory|null>(null);const [ready,setReady]=useState(false);const userId=user?.id??null;
useEffect(()=>{let active=true;setReady(false);void(async()=>{if(!eventId){setEntry(null);setReady(true);return}if(userId){const {eventMap}=await ensureEventMigration(userId);const cloudEventId=eventMap[eventId]??eventId;let found=await getCloudConcertMemory(cloudEventId);if(!found&&localStorage.getItem(MIGRATION_KEY)!==userId){const old=read().find(x=>x.eventId===eventId);if(old){let photo=old.photo||"";const draft={seat:old.seat||"",unforgettableMoment:old.unforgettableMoment||"",photo};found=await saveCloudConcertMemory(userId,cloudEventId,idolId||"",draft);if(photo&&isDataUrl(photo)){const ref=await uploadImage(userId,"concert-memories",cloudEventId,photo);if(ref)found=await saveCloudConcertMemory(userId,cloudEventId,idolId||"",{...draft,photo:ref})}}localStorage.setItem(MIGRATION_KEY,userId)}if(active)setEntry(found)}else if(active)setEntry(read().find(x=>x.eventId===eventId)??null);if(active)setReady(true)})().catch(()=>{if(active)setReady(true)});return()=>{active=false}},[eventId,idolId,userId]);
const save=useCallback(async(d:ConcertPersonalMemoryDraft)=>{if(!eventId)throw new Error("找不到這場演唱會");if(userId){let draft=d;if(d.photo&&isDataUrl(d.photo)){const ref=await uploadImage(userId,"concert-memories",eventId,d.photo);if(ref)draft={...d,photo:ref}}const saved=await saveCloudConcertMemory(userId,eventId,idolId||"",draft);setEntry(saved);return saved}const now=new Date().toISOString(),current=read(),previous=current.find(x=>x.eventId===eventId);const nextEntry:ConcertPersonalMemory={eventId,seat:d.seat.trim()||undefined,unforgettableMoment:d.unforgettableMoment.trim()||undefined,photo:d.photo||undefined,createdAt:previous?.createdAt??now,updatedAt:now};write([nextEntry,...current.filter(x=>x.eventId!==eventId)]);setEntry(nextEntry);return nextEntry},[eventId,idolId,userId]);
return useMemo(()=>({entry,ready:ready&&!loading,save}),[entry,ready,loading,save])}
