import { useRef,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Heart,Plus,X,Camera,Trash2 } from "lucide-react";
import { AppShell,PageHeader,SoftCard } from "@/components/AppShell";
import { COLLECTION_CATEGORIES,COLLECTION_PROVENANCE_OPTIONS,collectionCategoryMeta,type CollectionCategory,type CollectionItem,type CollectionProvenance } from "@/lib/collection";
import { useCollectionSource } from "@/lib/collection.source";
import { useIdolSource } from "@/lib/idols.source";
import { useEventSource } from "@/lib/events.source";
import { eventTypeMeta } from "@/lib/events";

export const Route=createFileRoute("/collection")({validateSearch:(s:Record<string,unknown>)=>({event:typeof s.event==="string"?s.event:undefined}),component:CollectionPage});
function CollectionPage(){
 const search=Route.useSearch();
 const {items,ready,addItem,updateItem,removeItem}=useCollectionSource(); const {idols,homeIdol}=useIdolSource(); const {events}=useEventSource();
 const inputRef=useRef<HTMLInputElement>(null); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<CollectionItem|null>(null);
 const [category,setCategory]=useState<CollectionCategory>("ALBUM"); const [provenance,setProvenance]=useState<CollectionProvenance>("UNSPECIFIED"); const [eventId,setEventId]=useState(search.event||""); const [title,setTitle]=useState(""); const [photo,setPhoto]=useState(""); const [date,setDate]=useState(""); const [source,setSource]=useState(""); const [note,setNote]=useState(""); const [favorite,setFavorite]=useState(false);
 const reset=()=>{setEditing(null);setCategory("ALBUM");setProvenance("UNSPECIFIED");setEventId("");setTitle("");setPhoto("");setDate("");setSource("");setNote("");setFavorite(false)};
 const startNew=()=>{reset();setEventId(search.event||"");setOpen(true)};
 const startEdit=(i:CollectionItem)=>{setEditing(i);setCategory(i.category);setProvenance(i.provenance||"UNSPECIFIED");setEventId(i.eventId||"");setTitle(i.title);setPhoto(i.photo||"");setDate(i.acquiredDate||"");setSource(i.source||"");setNote(i.note||"");setFavorite(i.favorite);setOpen(true)};
 const choosePhoto=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setPhoto(typeof reader.result==="string"?reader.result:"");reader.readAsDataURL(file)};
 const submit=async()=>{if(!title.trim())return;const draft={idolId:editing?.idolId||homeIdol?.id,eventId:eventId||undefined,category,provenance,title:title.trim(),photo:photo||undefined,acquiredDate:date||undefined,source:source.trim()||undefined,note:note.trim()||undefined,favorite};if(editing)await updateItem(editing.id,draft);else await addItem(draft);setOpen(false);reset()};
 return <AppShell>
  <PageHeader title="我的收藏 💎" subtitle="專輯・小卡・票根・應援物 ♡" />
  <section className="mb-6 grid grid-cols-3 gap-2">{COLLECTION_CATEGORIES.map(k=>{const m=collectionCategoryMeta[k],n=items.filter(i=>i.category===k).length;return <SoftCard key={k} className="px-3 py-4 text-center"><div className="text-2xl">{m.emoji}</div><p className="mt-2 text-sm font-medium">{m.label}</p><p className="mt-1 text-[13px] text-muted-foreground">{n}</p></SoftCard>})}</section>
  <button type="button" onClick={startNew} className="mb-6 flex min-h-[50px] w-full items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 text-base font-medium text-primary-foreground active:scale-[.98]"><Plus className="size-4"/>留下新的收藏</button>
  {!ready?<div className="h-32 rounded-3xl bg-surface/50"/>:items.length===0?<SoftCard className="px-5 py-8 text-center"><p className="font-display text-[19px]">第一件收藏，從喜歡開始 ♡</p><p className="mt-2 text-sm text-muted-foreground">專輯、小卡、票根或一件捨不得丟掉的周邊，都可以留在這裡。</p></SoftCard>:<div className="grid grid-cols-2 gap-3">{items.map(i=>{const m=collectionCategoryMeta[i.category];const idol=i.idolId?idols.find(x=>x.id===i.idolId):undefined;const linkedEvent=i.eventId?events.find(e=>e.id===i.eventId):undefined;const provenanceMeta=COLLECTION_PROVENANCE_OPTIONS.find(o=>o.value===(i.provenance||"UNSPECIFIED"));return <button key={i.id} type="button" onClick={()=>startEdit(i)} className="text-left active:scale-[.98]"><SoftCard className="h-full overflow-hidden p-0">{i.photo?<img src={i.photo} alt="" className="aspect-square w-full object-cover"/>:<div className="flex aspect-square items-center justify-center bg-gradient-to-br from-accent/35 to-card text-4xl">{m.emoji}</div>}<div className="px-4 py-3"><div className="flex items-start gap-2"><p className="min-w-0 flex-1 truncate text-base font-medium">{i.title}</p>{i.favorite?<Heart className="size-4 shrink-0 fill-current text-primary"/>:null}</div><p className="mt-1 truncate text-[13px] text-muted-foreground">{[m.label,idol?.name].filter(Boolean).join(" · ")}</p>{i.provenance&&i.provenance!=="UNSPECIFIED"?<p className="mt-1 truncate text-[12px] text-muted-foreground">{provenanceMeta?.emoji} {provenanceMeta?.label}</p>:null}{linkedEvent?<p className="mt-1 truncate text-[12px] text-primary">{eventTypeMeta(linkedEvent.type).emoji} {linkedEvent.title}</p>:null}</div></SoftCard></button>})}</div>}
  {open?<div className="fixed inset-0 z-[90] flex items-end bg-black/20" onClick={()=>{setOpen(false);reset()}}><div className="max-h-[90dvh] w-full overflow-y-auto rounded-t-[2rem] bg-card px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-4 shadow-xl" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><div><p className="text-[13px] font-semibold tracking-[.14em] text-primary">MY COLLECTION ♡</p><h2 className="mt-1 font-display text-[20px] font-semibold">{editing?"這件收藏":"留下新的收藏"}</h2></div><button onClick={()=>{setOpen(false);reset()}} className="flex size-11 items-center justify-center"><X className="size-5"/></button></div>
   <input ref={inputRef} type="file" accept="image/*" className="hidden" onChange={e=>choosePhoto(e.target.files?.[0])}/><button type="button" onClick={()=>inputRef.current?.click()} className="mb-4 flex aspect-[16/9] w-full items-center justify-center overflow-hidden rounded-[1.5rem] bg-surface">{photo?<img src={photo} alt="收藏照片" className="h-full w-full object-cover"/>:<span className="flex flex-col items-center gap-2 text-sm text-muted-foreground"><Camera className="size-6"/>＋ 照片</span>}</button>
   <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{COLLECTION_CATEGORIES.map(k=><button key={k} onClick={()=>setCategory(k)} className={`shrink-0 rounded-full px-3 py-2 text-sm ${category===k?"bg-primary text-primary-foreground":"bg-surface"}`}>{collectionCategoryMeta[k].emoji} {collectionCategoryMeta[k].label}</button>)}</div>
   <div><p className="mb-2 text-[13px] font-medium text-muted-foreground">來源</p><div className="flex gap-2 overflow-x-auto pb-1">{COLLECTION_PROVENANCE_OPTIONS.map(o=><button key={o.value} type="button" onClick={()=>setProvenance(o.value)} className={`shrink-0 rounded-full px-3 py-2 text-sm ${provenance===o.value?"bg-primary text-primary-foreground":"bg-surface"}`}>{o.emoji} {o.label}</button>)}</div></div><div className="space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="收藏名稱" className="min-h-[50px] w-full rounded-2xl bg-surface px-4 text-base outline-none"/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="min-h-[50px] w-full rounded-2xl bg-surface px-4 text-base outline-none"/><select value={eventId} onChange={e=>setEventId(e.target.value)} className="min-h-[50px] w-full rounded-2xl bg-surface px-4 text-base outline-none"><option value="">連到哪個追星日？（選填）</option>{events.filter(e=>!homeIdol?.id||e.idolId===homeIdol.id).map(e=><option key={e.id} value={e.id}>{eventTypeMeta(e.type).emoji} {e.title} · {e.date}</option>)}</select><input value={source} onChange={e=>setSource(e.target.value)} placeholder="哪裡入手？（選填）" className="min-h-[50px] w-full rounded-2xl bg-surface px-4 text-base outline-none"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="想留一句？（選填）" className="min-h-24 w-full rounded-2xl bg-surface px-4 py-3 text-base outline-none"/></div>
   <button type="button" onClick={()=>setFavorite(v=>!v)} className={`mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-full border px-4 text-sm ${favorite?"border-primary/30 bg-primary/10 text-primary":"border-border/60"}`}><Heart className={`size-4 ${favorite?"fill-current":""}`}/>{favorite?"最喜歡的收藏 ♡":"標記為最喜歡 ♡"}</button>
   <button disabled={!title.trim()} onClick={()=>void submit()} className="mt-4 min-h-[52px] w-full rounded-full bg-primary px-5 text-base font-medium text-primary-foreground disabled:opacity-40">{editing?"儲存這件收藏":"收進我的收藏 ♡"}</button>
   {editing?<button type="button" onClick={async()=>{if(!confirm("要刪除這件收藏嗎？"))return;await removeItem(editing.id);setOpen(false);reset()}} className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 text-sm text-destructive"><Trash2 className="size-4"/>刪除收藏</button>:null}
  </div></div>:null}
 </AppShell>
}
