/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchaeologyRouteImport } from './routes/archaeology'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IdolsRouteImport } from './routes/idols'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchaeologyRoute = ArchaeologyRouteImport.update({
  id: '/archaeology',
  path: '/archaeology',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IdolsRoute = IdolsRouteImport.update({
  id: '/idols',
  path: '/idols',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archaeology': typeof ArchaeologyRoute
  '/calendar': typeof CalendarRoute
  '/idols': typeof IdolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archaeology': typeof ArchaeologyRoute
  '/calendar': typeof CalendarRoute
  '/idols': typeof IdolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archaeology': typeof ArchaeologyRoute
  '/calendar': typeof CalendarRoute
  '/idols': typeof IdolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archaeology' | '/calendar' | '/idols'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archaeology' | '/calendar' | '/idols'
  id: '__root__' | '/' | '/archaeology' | '/calendar' | '/idols'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchaeologyRoute: typeof ArchaeologyRoute
  CalendarRoute: typeof CalendarRoute
  IdolsRoute: typeof IdolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archaeology': {
      id: '/archaeology'
      path: '/archaeology'
      fullPath: '/archaeology'
      preLoaderRoute: typeof ArchaeologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idols': {
      id: '/idols'
      path: '/idols'
      fullPath: '/idols'
      preLoaderRoute: typeof IdolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchaeologyRoute: ArchaeologyRoute,
  CalendarRoute: CalendarRoute,
  IdolsRoute: IdolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
