/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchaeologyRouteImport } from './routes/archaeology'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HeartRouteImport } from './routes/heart'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IdolsRouteImport } from './routes/idols'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminIdolsRouteImport } from './routes/admin.idols'
import { Route as AdminMemoriesRouteImport } from './routes/admin.memories'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminSugarRouteImport } from './routes/admin.sugar'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWidgetRouteImport } from './routes/admin.widget'
import { Route as ApiLinkPreviewRouteImport } from './routes/api.link-preview'
import { Route as ApiLinkPreviewImageRouteImport } from './routes/api.link-preview-image'
import { Route as ApiWeatherRouteImport } from './routes/api.weather'
import { Route as IdolsIdolIdRouteImport } from './routes/idols.$idolId'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as MemoriesFolderIdRouteImport } from './routes/memories.$folderId'
import { Route as ReceiveCodeRouteImport } from './routes/receive.$code'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as WeatherEventIdRouteImport } from './routes/weather.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchaeologyRoute = ArchaeologyRouteImport.update({
  id: '/archaeology',
  path: '/archaeology',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartRoute = HeartRouteImport.update({
  id: '/heart',
  path: '/heart',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IdolsRoute = IdolsRouteImport.update({
  id: '/idols',
  path: '/idols',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdolsRoute = AdminIdolsRouteImport.update({
  id: '/idols',
  path: '/idols',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoriesRoute = AdminMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSugarRoute = AdminSugarRouteImport.update({
  id: '/sugar',
  path: '/sugar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWidgetRoute = AdminWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AdminRoute,
} as any)
const ApiLinkPreviewRoute = ApiLinkPreviewRouteImport.update({
  id: '/api/link-preview',
  path: '/api/link-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewImageRoute = ApiLinkPreviewImageRouteImport.update({
  id: '/api/link-preview-image',
  path: '/api/link-preview-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const IdolsIdolIdRoute = IdolsIdolIdRouteImport.update({
  id: '/$idolId',
  path: '/$idolId',
  getParentRoute: () => IdolsRoute,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesFolderIdRoute = MemoriesFolderIdRouteImport.update({
  id: '/memories/$folderId',
  path: '/memories/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveCodeRoute = ReceiveCodeRouteImport.update({
  id: '/receive/$code',
  path: '/receive/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherEventIdRoute = WeatherEventIdRouteImport.update({
  id: '/weather/$eventId',
  path: '/weather/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/archaeology': typeof ArchaeologyRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/collection': typeof CollectionRoute
  '/events': typeof EventsRoute
  '/heart': typeof HeartRoute
  '/home': typeof HomeRoute
  '/idols': typeof IdolsRouteWithChildren
  '/intro': typeof IntroRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/widget': typeof WidgetRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/idols': typeof AdminIdolsRoute
  '/admin/memories': typeof AdminMemoriesRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/sugar': typeof AdminSugarRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/widget': typeof AdminWidgetRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/link-preview-image': typeof ApiLinkPreviewImageRoute
  '/api/weather': typeof ApiWeatherRoute
  '/idols/$idolId': typeof IdolsIdolIdRoute
  '/memories/$folderId': typeof MemoriesFolderIdRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/shared/$token': typeof SharedTokenRoute
  '/weather/$eventId': typeof WeatherEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archaeology': typeof ArchaeologyRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/collection': typeof CollectionRoute
  '/events': typeof EventsRoute
  '/heart': typeof HeartRoute
  '/home': typeof HomeRoute
  '/idols': typeof IdolsRouteWithChildren
  '/intro': typeof IntroRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/widget': typeof WidgetRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/idols': typeof AdminIdolsRoute
  '/admin/memories': typeof AdminMemoriesRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/sugar': typeof AdminSugarRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/widget': typeof AdminWidgetRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/link-preview-image': typeof ApiLinkPreviewImageRoute
  '/api/weather': typeof ApiWeatherRoute
  '/idols/$idolId': typeof IdolsIdolIdRoute
  '/memories/$folderId': typeof MemoriesFolderIdRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/shared/$token': typeof SharedTokenRoute
  '/weather/$eventId': typeof WeatherEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/archaeology': typeof ArchaeologyRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/collection': typeof CollectionRoute
  '/events': typeof EventsRoute
  '/heart': typeof HeartRoute
  '/home': typeof HomeRoute
  '/idols': typeof IdolsRouteWithChildren
  '/intro': typeof IntroRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/widget': typeof WidgetRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/idols': typeof AdminIdolsRoute
  '/admin/memories': typeof AdminMemoriesRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/sugar': typeof AdminSugarRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/widget': typeof AdminWidgetRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/link-preview-image': typeof ApiLinkPreviewImageRoute
  '/api/weather': typeof ApiWeatherRoute
  '/idols/$idolId': typeof IdolsIdolIdRoute
  '/memories/$folderId': typeof MemoriesFolderIdRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/shared/$token': typeof SharedTokenRoute
  '/weather/$eventId': typeof WeatherEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archaeology'
    | '/auth'
    | '/calendar'
    | '/collection'
    | '/events'
    | '/heart'
    | '/home'
    | '/idols'
    | '/intro'
    | '/music'
    | '/profile'
    | '/widget'
    | '/admin/events'
    | '/admin/idols'
    | '/admin/memories'
    | '/admin/reminders'
    | '/admin/sugar'
    | '/admin/users'
    | '/admin/widget'
    | '/api/link-preview'
    | '/api/link-preview-image'
    | '/api/weather'
    | '/idols/$idolId'
    | '/memories/$folderId'
    | '/receive/$code'
    | '/shared/$token'
    | '/weather/$eventId'
    | '/admin/'
    | '/memories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archaeology'
    | '/auth'
    | '/calendar'
    | '/collection'
    | '/events'
    | '/heart'
    | '/home'
    | '/idols'
    | '/intro'
    | '/music'
    | '/profile'
    | '/widget'
    | '/admin/events'
    | '/admin/idols'
    | '/admin/memories'
    | '/admin/reminders'
    | '/admin/sugar'
    | '/admin/users'
    | '/admin/widget'
    | '/api/link-preview'
    | '/api/link-preview-image'
    | '/api/weather'
    | '/idols/$idolId'
    | '/memories/$folderId'
    | '/receive/$code'
    | '/shared/$token'
    | '/weather/$eventId'
    | '/admin'
    | '/memories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archaeology'
    | '/auth'
    | '/calendar'
    | '/collection'
    | '/events'
    | '/heart'
    | '/home'
    | '/idols'
    | '/intro'
    | '/music'
    | '/profile'
    | '/widget'
    | '/admin/events'
    | '/admin/idols'
    | '/admin/memories'
    | '/admin/reminders'
    | '/admin/sugar'
    | '/admin/users'
    | '/admin/widget'
    | '/api/link-preview'
    | '/api/link-preview-image'
    | '/api/weather'
    | '/idols/$idolId'
    | '/memories/$folderId'
    | '/receive/$code'
    | '/shared/$token'
    | '/weather/$eventId'
    | '/admin/'
    | '/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchaeologyRoute: typeof ArchaeologyRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CollectionRoute: typeof CollectionRoute
  EventsRoute: typeof EventsRoute
  HeartRoute: typeof HeartRoute
  HomeRoute: typeof HomeRoute
  IdolsRoute: typeof IdolsRouteWithChildren
  IntroRoute: typeof IntroRoute
  MusicRoute: typeof MusicRoute
  ProfileRoute: typeof ProfileRoute
  WidgetRoute: typeof WidgetRoute
  ApiLinkPreviewRoute: typeof ApiLinkPreviewRoute
  ApiLinkPreviewImageRoute: typeof ApiLinkPreviewImageRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  MemoriesFolderIdRoute: typeof MemoriesFolderIdRoute
  ReceiveCodeRoute: typeof ReceiveCodeRoute
  SharedTokenRoute: typeof SharedTokenRoute
  WeatherEventIdRoute: typeof WeatherEventIdRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archaeology': {
      id: '/archaeology'
      path: '/archaeology'
      fullPath: '/archaeology'
      preLoaderRoute: typeof ArchaeologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heart': {
      id: '/heart'
      path: '/heart'
      fullPath: '/heart'
      preLoaderRoute: typeof HeartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idols': {
      id: '/idols'
      path: '/idols'
      fullPath: '/idols'
      preLoaderRoute: typeof IdolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/idols': {
      id: '/admin/idols'
      path: '/idols'
      fullPath: '/admin/idols'
      preLoaderRoute: typeof AdminIdolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memories': {
      id: '/admin/memories'
      path: '/memories'
      fullPath: '/admin/memories'
      preLoaderRoute: typeof AdminMemoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sugar': {
      id: '/admin/sugar'
      path: '/sugar'
      fullPath: '/admin/sugar'
      preLoaderRoute: typeof AdminSugarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/widget': {
      id: '/admin/widget'
      path: '/widget'
      fullPath: '/admin/widget'
      preLoaderRoute: typeof AdminWidgetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/link-preview': {
      id: '/api/link-preview'
      path: '/api/link-preview'
      fullPath: '/api/link-preview'
      preLoaderRoute: typeof ApiLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview-image': {
      id: '/api/link-preview-image'
      path: '/api/link-preview-image'
      fullPath: '/api/link-preview-image'
      preLoaderRoute: typeof ApiLinkPreviewImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idols/$idolId': {
      id: '/idols/$idolId'
      path: '/$idolId'
      fullPath: '/idols/$idolId'
      preLoaderRoute: typeof IdolsIdolIdRouteImport
      parentRoute: typeof IdolsRoute
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$folderId': {
      id: '/memories/$folderId'
      path: '/memories/$folderId'
      fullPath: '/memories/$folderId'
      preLoaderRoute: typeof MemoriesFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive/$code': {
      id: '/receive/$code'
      path: '/receive/$code'
      fullPath: '/receive/$code'
      preLoaderRoute: typeof ReceiveCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/$eventId': {
      id: '/weather/$eventId'
      path: '/weather/$eventId'
      fullPath: '/weather/$eventId'
      preLoaderRoute: typeof WeatherEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminIdolsRoute: typeof AdminIdolsRoute
  AdminMemoriesRoute: typeof AdminMemoriesRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminSugarRoute: typeof AdminSugarRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWidgetRoute: typeof AdminWidgetRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminIdolsRoute: AdminIdolsRoute,
  AdminMemoriesRoute: AdminMemoriesRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminSugarRoute: AdminSugarRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWidgetRoute: AdminWidgetRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface IdolsRouteChildren {
  IdolsIdolIdRoute: typeof IdolsIdolIdRoute
}

const IdolsRouteChildren: IdolsRouteChildren = {
  IdolsIdolIdRoute: IdolsIdolIdRoute,
}

const IdolsRouteWithChildren = IdolsRoute._addFileChildren(IdolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchaeologyRoute: ArchaeologyRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CollectionRoute: CollectionRoute,
  EventsRoute: EventsRoute,
  HeartRoute: HeartRoute,
  HomeRoute: HomeRoute,
  IdolsRoute: IdolsRouteWithChildren,
  IntroRoute: IntroRoute,
  MusicRoute: MusicRoute,
  ProfileRoute: ProfileRoute,
  WidgetRoute: WidgetRoute,
  ApiLinkPreviewRoute: ApiLinkPreviewRoute,
  ApiLinkPreviewImageRoute: ApiLinkPreviewImageRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  MemoriesFolderIdRoute: MemoriesFolderIdRoute,
  ReceiveCodeRoute: ReceiveCodeRoute,
  SharedTokenRoute: SharedTokenRoute,
  WeatherEventIdRoute: WeatherEventIdRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
